# Generated by Django 3.2.9 on 2022-01-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tougshireauthgroup',
            name='short_name',
            field=models.CharField(blank=True, help_text='A short, (preferably single-letter) designation for the group used in list display', max_length=3, verbose_name='short name'),
        ),
    ]
