# Generated by Django 4.0.4 on 2022-05-05 20:04

from django.db import migrations
import tougshire_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_auth', '0002_tougshireauthgroup_short_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tougshireauthuser',
            managers=[
                ('objects', tougshire_auth.models.OptionsUserManager()),
            ],
        ),
    ]
